package com.boomhope.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.boomhope.po.DeployUnit;
@Repository
public interface DeployUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_unit
     *
     * @mbg.generated
     */
	void deleteByPrimaryKey(List<String> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_unit
     *
     * @mbg.generated
     */
    int insert(DeployUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_unit
     *
     * @mbg.generated
     */
    DeployUnit selectByPrimaryKey(String unitCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_unit
     *
     * @mbg.generated
     */
    List<DeployUnit> selectAll(String unitName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeployUnit record);
    
    /**
     * 启用禁用单独方法
     */
    void updateByPrimaryKeySelective(DeployUnit record);
    
    /**
     * 根据指定条件查询数据
     * @param map
     * @return
     */
    List<DeployUnit> findDeployUnitList(Map<String,String> map);
    
    /**
     * 根据机构名称获取机构信息
     * @param unitName
     * @return
     */
    DeployUnit selectByUnitName(String unitName);
    
    /**
     * 查询所有unit_name
     * @return
     */
    List<String> selectUnitName();
    
    List<DeployUnit> findBusinessManagentList(Map<String,String>parMap);
    
    /**
     * 导入excel的插入
     */
    void importInsert(List<DeployUnit> list);
    
}