package com.boomhope.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.boomhope.po.SysAdmin;;

@Repository
public interface SysAdminMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_admin
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("ids") List<String> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_admin
	 *
	 * @mbg.generated
	 */
	void deleteAdminList(@Param("userIds") List<String> userIds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_admin
	 *
	 * @mbg.generated
	 */
	int insert(SysAdmin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_admin
	 *
	 * @mbg.generated
	 */
	SysAdmin selectByPrimaryKey(String loginName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_admin
	 *
	 * @mbg.generated
	 */
	List<SysAdmin> selectByUserName(String userName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_admin
	 *
	 * @mbg.generated
	 */
	List<SysAdmin> selectAllList(Map<String, String> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_admin
	 *
	 * @mbg.generated
	 */
	List<SysAdmin> selectAll();

	/**
	 * 用户更新
	 * 
	 * @param loginName
	 */
	int updateByPrimaryKey(SysAdmin sysAdmin);

	/**
	 * 用户状态
	 * 
	 * @param loginName
	 */
	public List<String> selectStatusByloginName(@Param("userIds") List<String> userIds);

	/**
	 * 用户名+密码查询
	 * 
	 * @param loginName
	 * @param password
	 * @return
	 */
	List<SysAdmin> findSysAdmin(String loginName, String password);

}