package com.boomhope.dao;

import com.boomhope.po.SysMenu;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository
public interface SysMenuMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 *
	 * @mbg.generated
	 */
	int insert(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 *
	 * @mbg.generated
	 */
	SysMenu selectByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 *
	 * @mbg.generated
	 */
	List<SysMenu> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_menu
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SysMenu record);
}