package com.boomhope.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.boomhope.po.SysRole;

@Repository
public interface SysRoleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("roleCodes") List<String> roleCodes);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 *
	 * @mbg.generated
	 */
	int insert(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 *
	 * @mbg.generated
	 */
	SysRole selectByPrimaryKey(Integer roleCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 *
	 * @mbg.generated
	 */
	List<SysRole> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_role
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SysRole sysRole);

	/**
	 * 根据角色名获取角色信息(添加角色时筛选重复数据)
	 * 
	 * @param roleName
	 * @return
	 */
	SysRole selectByRoleName(String roleName);

	/**
	 * 根据角色名获取角色信息(模糊匹配角色名)
	 * 
	 * @param roleName
	 * @return
	 */
	List<SysRole> selectByLikeRoleName(String roleName);

	/**
	 * 根据指定条件查询角色表数据
	 * 
	 * @param map
	 * @return
	 */
	List<SysRole> findSysRoleList(Map<String, String> map);

	/**
	 * 根据指定条件查询角色表数据
	 * 
	 * @param map
	 * @return
	 */
	List<SysRole> findUserRoleList(List list);

}