package com.boomhope.dao;

import com.boomhope.po.SysUserRoleMap;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository
public interface SysUserRoleMapMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_role_map
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_role_map
	 *
	 * @mbg.generated
	 */
	int insert(SysUserRoleMap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_role_map
	 *
	 * @mbg.generated
	 */
	SysUserRoleMap selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_role_map
	 *
	 * @mbg.generated
	 */
	SysUserRoleMap selectRoleCodeByPrimaryKey(String roleName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_role_map
	 *
	 * @mbg.generated
	 */
	List<SysUserRoleMap> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_role_map
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(SysUserRoleMap record);

	/**
	 * 查询登陆名
	 * 
	 * @param loginName
	 * @return
	 */
	List<SysUserRoleMap> selectByLoginName(List<String> list);
	
	/**
	 * 根据登陆名查询List
	 * 
	 * @param loginName
	 * @return
	 * added by zhangxx
	 */
	List<SysUserRoleMap> selectByLoginName1(String loginName);
	
	/**
	 * 根据登陆名删除信息
	 * 
	 * @param loginName
	 */
	void deleteByLoginName(String loginName);

	/**
	 * 添加用户角色
	 * 
	 * @param sysUserRoleMaps
	 */
	void saveUserRoleList(List<SysUserRoleMap> sysUserRoleMaps);
}