package com.boomhope.model;


public class DeployUnitVo {
	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.unit_code
     *
     * @mbg.generated
     */
    private String unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.unit_name
     *
     * @mbg.generated
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.unit_tel
     *
     * @mbg.generated
     */
    private String unitTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.manager
     *
     * @mbg.generated
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.parent_code
     *
     * @mbg.generated
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_unit.creater
     *
     * @mbg.generated
     */
    private String creater;

    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.unit_code
     *
     * @param unitCode the value for deploy_unit.unit_code
     *
     * @mbg.generated
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.unit_name
     *
     * @return the value of deploy_unit.unit_name
     *
     * @mbg.generated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.unit_name
     *
     * @param unitName the value for deploy_unit.unit_name
     *
     * @mbg.generated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.unit_tel
     *
     * @return the value of deploy_unit.unit_tel
     *
     * @mbg.generated
     */
    public String getUnitTel() {
        return unitTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.unit_tel
     *
     * @param unitTel the value for deploy_unit.unit_tel
     *
     * @mbg.generated
     */
    public void setUnitTel(String unitTel) {
        this.unitTel = unitTel == null ? null : unitTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.address
     *
     * @return the value of deploy_unit.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.address
     *
     * @param address the value for deploy_unit.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.manager
     *
     * @return the value of deploy_unit.manager
     *
     * @mbg.generated
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.manager
     *
     * @param manager the value for deploy_unit.manager
     *
     * @mbg.generated
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.email
     *
     * @return the value of deploy_unit.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.email
     *
     * @param email the value for deploy_unit.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.phone
     *
     * @return the value of deploy_unit.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.phone
     *
     * @param phone the value for deploy_unit.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.status
     *
     * @return the value of deploy_unit.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.status
     *
     * @param status the value for deploy_unit.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.parent_code
     *
     * @return the value of deploy_unit.parent_code
     *
     * @mbg.generated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.parent_code
     *
     * @param parentCode the value for deploy_unit.parent_code
     *
     * @mbg.generated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.create_date
     *
     * @return the value of deploy_unit.create_date
     *
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.create_date
     *
     * @param createDate the value for deploy_unit.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_unit.creater
     *
     * @return the value of deploy_unit.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_unit.creater
     *
     * @param creater the value for deploy_unit.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }
}